name = "possouscire"
type = "webpack"
account_id = "d5d4cf1d9375c96a4a4cc5785ce6d554"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "../../dist/apps/possouscire/exported"
entry-point = "site-worker"
